export const CertificationOptions = [
    "N/A - No certifications completed",
    "AWS Certification",
    "Azure Certification",
    "CompTIA A+",
    "CompTIA AI Essentials",
    "CompTIA AI Prompting Essentials",
    "CompTIA Security+",
    "Front End Development Libraries",
    "Google Cloud Certification",
    "Google IT Support",
    "Intro to AI Ethics",
    "Intro to Deep Learning",
    "Intro to Machine Learning",
    "Java (Basic) Certification",
    "Problem Solving (Basic)",
    "Programming Foundations: Fundamentals",
    "Quality Assurance Certification",
    "Relational Databases Certification",
    "Responsive Web Design",
    "REST API (Intermediate)",
    "Scrum Master",
    "Software Engineer Certification",
    "SQL (Basic) Certification",
    "Other/Custom Entry",
]